'use strict';
/**
 * Bearer tokens for remote-agent authentication (Partie 2 — hôtes Docker
 * distants, voir le document de conception du Projet Claude). Same shape of
 * problem as lib/deploy-tokens.js — a bearer secret that must authenticate
 * as a narrow, revocable scope, never the global admin token — but a
 * different lifecycle: a deploy token is a handful of entries an operator
 * types into a YAML file by hand; an agent token is generated by the server
 * itself the moment an operator approves an enrollment request
 * (features/agents.js), shown to that operator exactly once, and must never
 * be recoverable again afterwards.
 *
 * Only the SHA-256 hash of a token is ever persisted (in the agents registry,
 * see features/agents.js's use of lib/events.js's state table) — exactly
 * like a password hash never stores the plaintext (lib/auth.js). A leaked
 * state table (a backup, a debug dump, a copy-pasted support log) still
 * never yields a token an attacker could actually present at
 * POST /api/agent/manifest.
 */
const crypto = require('crypto');

const TOKEN_PREFIX = 'agt_';

/** A fresh random token: 24 bytes (192 bits) of entropy, hex-encoded. */
function generateToken() {
  return TOKEN_PREFIX + crypto.randomBytes(24).toString('hex');
}

/** SHA-256 hex digest — never the raw token — is what gets persisted. */
function hashToken(rawToken) {
  return crypto.createHash('sha256').update(String(rawToken || '')).digest('hex');
}

/**
 * Constant-time comparison of two hex-encoded SHA-256 digests. Both are
 * always 64 hex chars when produced by hashToken(), so this never leaks a
 * length-based timing signal either — unlike comparing raw tokens of
 * attacker-controlled length, which is why lib/auth.js's safeCompare()
 * bails out (mismatched-length branch) before ever calling
 * timingSafeEqual() on unequal-length buffers.
 */
function safeCompareHash(a, b) {
  try {
    const ba = Buffer.from(String(a || ''), 'hex');
    const bb = Buffer.from(String(b || ''), 'hex');
    if (ba.length !== bb.length || ba.length === 0) return false;
    return crypto.timingSafeEqual(ba, bb);
  } catch { return false; }
}

module.exports = { TOKEN_PREFIX, generateToken, hashToken, safeCompareHash };
