'use strict';
/**
 * Deployment pipeline and backups.
 *
 * Pull -> test in a throwaway container -> back up -> copy -> reload. The test
 * is the point of the whole thing, and it earned its complexity the hard way:
 *
 *  - Bind-mount sources must be HOST paths. Handing the daemon a path that only
 *    exists inside this container makes it create an empty directory and mount
 *    that, so the test validated nothing while reporting success.
 *  - The sandbox inherits the production container's mounts, minus the config
 *    directories it replaces. Hardcoding the list meant every mount an operator
 *    added later — GeoIP databases, webroot — broke `nginx -t`.
 *  - It runs on the production network. nginx resolves upstream hostnames while
 *    parsing, so an isolated container fails on every `upstream` naming a real
 *    host.
 *
 * Copying is recursive: config trees are not flat, and `ssl/<ca>/` was being
 * silently dropped. Deletions skip dotfiles and are abandoned entirely when the
 * source directory is empty — a repo folder holding only a `.gitkeep` would
 * otherwise wipe the live configuration.
 *
 * Without a Git repository the copy is additive only: the work tree then holds
 * a subset of the configuration, so removing what is missing from it would
 * delete files that were never managed here.
 */

const fs   = require('fs');
const path = require('path');

const cfg     = require('../lib/config');
const httpLib = require('../lib/http');
const auth    = require('../lib/auth');
const docker  = require('../lib/docker');
const tree    = require('../lib/fs-tree');
const git     = require('../lib/git');
const backup  = require('../lib/backup');
const events  = require('../lib/events');

const { PERMS, hasPerm, deployTokenAllows } = auth;
const { send, parseBody } = httpLib;
const { dockerCall, execNginx, toHostPath, getContainerId, getNginxNetworkMode } = docker;
const { safeStat, listTreeFiles, copyTree, pruneEmptyDirs, isDirWritable, isProtectedFile } = tree;
const { runCmd, gitPull, gitDiff, ensureGitRepo, effectiveRepoUrl, gitBackupPush,
        gitTestConnection, gitCreateBackupBranch, getGitCfg, validateBranch, redactUrl } = git;
const { createBackupZip, listBackups, restoreBackupZip, rotateBackups } = backup;
const { logEvent } = events;
const {
  DIR_GIT_WORK, DIR_BACKUPS, DIR_SITES, DIR_CONF, DIR_SNIPPETS, DIR_STREAMS,
  DIR_SSL, DIR_CERTS, DEPLOY_SYNC_SSL, NGINX_IMAGE, NGINX_CONTAINER, BACKUP_KEEP,
} = cfg;

// Historic alias: the ephemeral test asks for the same network as production.
const getTestNetworkMode = getNginxNetworkMode;

/**
 * Absolute paths of files that live under one of the four Git-synced
 * directories (sites/conf/snippets/streams) but are generated by another
 * feature at runtime, not tracked in the repository — features/blocklists.js
 * is the first case (blocklist-ips.conf, blocklist-enforce.conf). A Git
 * deploy's full mirror sync must never delete them just because they are
 * absent from the repo, and the ephemeral `nginx -t` test must see them
 * exactly as they exist in production, or a vhost that legitimately
 * `include`s one of them would fail every Git deploy.
 *
 * Set via setDeps(), same composition-root pattern as every other
 * cross-feature dependency in this project (features never import each
 * other directly) — empty until server.js wires it, so this file works even
 * if the caller happens to load before blocklists.js does.
 *
 * `generatedFiles` may be a plain array (blocklists.js's original, fixed-size
 * case) OR a function returning the current list (features/docker-autoconfig.js's
 * case: one file per labelled container, appearing/disappearing at runtime —
 * a static array captured once at boot would go stale the moment a container
 * starts or stops). getGeneratedFilesList() below resolves either shape.
 */
let generatedFiles = [];

function setDeps({ generatedFiles: g } = {}) {
  if (Array.isArray(g) || typeof g === 'function') generatedFiles = g;
}

function getGeneratedFilesList() {
  return typeof generatedFiles === 'function' ? (generatedFiles() || []) : generatedFiles;
}

// Filename prefixes reserved by features that generate their own sites/*.conf
// files at runtime — features/docker-autoconfig.js (Partie 1, one file per
// labelled container) and features/agents.js (Partie 2, one file per vhost a
// remote agent's manifest describes). A second, independent list from
// GENERATED_FILES() itself: belt and suspenders, since a feature's own list
// (from its last completed cycle) could be momentarily stale right after a
// restart, but a prefix on disk never is.
const GENERATED_FILE_PREFIXES = ['docker_', 'agent_'];

/**
 * True when `absPath` is one of the externally-generated files above, either
 * by exact membership in the injected list, or — a second, independent
 * check — by living in DIR_SITES with one of GENERATED_FILE_PREFIXES.
 */
function isGeneratedFile(absPath) {
  if (getGeneratedFilesList().includes(absPath)) return true;
  return path.dirname(absPath) === DIR_SITES
    && GENERATED_FILE_PREFIXES.some(p => path.basename(absPath).startsWith(p));
}

/**
 * Builds the `sites/conf/snippets/streams` source directories an ephemeral
 * `nginx -t` test should read, for ANY route that tests the raw Git work
 * tree — overlaying, on top of each section's git-work content, whichever
 * externally-generated files (see isGeneratedFile above) belong to that
 * section and currently exist in production.
 *
 * Without this, a vhost that legitimately includes a generated file (never
 * committed to the repo on purpose — see features/blocklists.js) fails
 * every single Git-based test, since git-work alone never has it. This
 * bit twice before being centralized here: once in deployFromGit()'s own
 * test step, and separately in the standalone `/api/git/test` route, which
 * built its own git-work-only srcDirs and was missed when the first fix
 * only touched deployFromGit(). Any future route that tests git-work must
 * go through this helper instead of listing DIR_GIT_WORK sections by hand.
 *
 * Returns { testSrcDirs, cleanup } — cleanup() removes the temporary merge
 * directory and must be called (in a finally) once the test has run.
 */
function buildGitWorkTestSrcDirs() {
  const activeDirBySection = { sites: DIR_SITES, conf: DIR_CONF, snippets: DIR_SNIPPETS, streams: DIR_STREAMS };
  const gitWorkDirBySection = {
    sites:    path.join(DIR_GIT_WORK, 'sites'),
    conf:     path.join(DIR_GIT_WORK, 'conf'),
    snippets: path.join(DIR_GIT_WORK, 'snippets'),
    streams:  path.join(DIR_GIT_WORK, 'streams'),
  };
  const mergeRoot = path.join(DIR_GIT_WORK, '.test-merge-generated');
  fs.rmSync(mergeRoot, { recursive: true, force: true });
  const allGenerated = getGeneratedFilesList();
  const testSrcDirs = {};
  for (const [section, gitWorkDir] of Object.entries(gitWorkDirBySection)) {
    const activeDir = activeDirBySection[section];
    const sectionGenerated = allGenerated.filter(f => path.dirname(f) === activeDir);
    // sites/ additionally picks up any docker_*.conf/agent_*.conf actually on
    // disk, even one this process has never itself generated (e.g. right
    // after a restart, before features/docker-autoconfig.js's or
    // features/agents.js's first cycle/push has run) — see
    // isGeneratedFile()'s own comment for why the prefix check is kept
    // independent of the injected list.
    if (activeDir === DIR_SITES) {
      try {
        for (const name of fs.readdirSync(DIR_SITES)) {
          if (!GENERATED_FILE_PREFIXES.some(p => name.startsWith(p))) continue;
          const fp = path.join(DIR_SITES, name);
          if (!sectionGenerated.includes(fp)) sectionGenerated.push(fp);
        }
      } catch { /* DIR_SITES missing — nothing to add */ }
    }
    if (!sectionGenerated.length) { testSrcDirs[section] = gitWorkDir; continue; }
    // Only sections that actually have a generated file get a merged
    // temp dir — everything else still points straight at git-work, no
    // needless copy.
    const mergeDir = path.join(mergeRoot, section);
    fs.mkdirSync(mergeDir, { recursive: true });
    copyTree(gitWorkDir, mergeDir);
    for (const f of sectionGenerated) {
      if (fs.existsSync(f)) fs.copyFileSync(f, path.join(mergeDir, path.basename(f)));
    }
    testSrcDirs[section] = mergeDir;
  }
  const cleanup = () => { try { fs.rmSync(mergeRoot, { recursive: true, force: true }); } catch {} };
  return { testSrcDirs, cleanup };
}

async function getNginxImage() {
  if (NGINX_IMAGE) return NGINX_IMAGE;
  // Auto-detect from running nginx container
  const id = await getContainerId();
  const r = await dockerCall('GET', `/containers/${encodeURIComponent(id)}/json`);
  if (r.status === 200 && r.body?.Config?.Image) return r.body.Config.Image;
  throw new Error('NGINX_IMAGE not configured and cannot auto-detect from running container');
}

/** Remove sandbox directories older than an hour (crash / restart leftovers). */
function cleanStaleSandboxes(sandboxRoot) {
  try {
    if (!fs.existsSync(sandboxRoot)) return;
    const cutoff = Date.now() - 3600_000;
    for (const d of fs.readdirSync(sandboxRoot)) {
      const p = path.join(sandboxRoot, d);
      if ((safeStat(p)?.mtimeMs || 0) < cutoff) fs.rmSync(p, { recursive: true, force: true });
    }
  } catch {}
}

/** One-off migration: earlier versions staged tests inside the backups folder. */
function cleanLegacyTestDirs() {
  try {
    if (!fs.existsSync(DIR_BACKUPS)) return;
    let cleaned = 0;
    for (const d of fs.readdirSync(DIR_BACKUPS)) {
      if (!d.startsWith('_test_')) continue;
      fs.rmSync(path.join(DIR_BACKUPS, d), { recursive: true, force: true });
      cleaned++;
    }
    if (cleaned) console.log(`[backup] Removed ${cleaned} leftover test dir(s) from ${DIR_BACKUPS}`);
  } catch {}
}

/**
 * Bind mounts for the ephemeral test container.
 *
 * The sandbox holds the configuration under test; everything else nginx needs
 * to parse it — GeoIP databases, webroot, extra module configs — is inherited
 * from the production container. Hardcoding the list meant every new mount an
 * operator added silently broke `nginx -t`: first the certificates, then the
 * GeoIP databases, each time with a failure that looked like a config error.
 *
 * Inherited mounts are forced read-only: the test must never touch production
 * data. Directories nginx writes to are skipped entirely — mounting them
 * read-only would make `nginx -t` fail on opening its log files, and the image
 * already provides writable ones.
 */
async function buildTestBinds(hostTmpDir) {
  // Destinations the sandbox replaces.
  const overridden = new Set([
    '/etc/nginx/sites', '/etc/nginx/conf.d', '/etc/nginx/snippets',
    '/etc/nginx/streams', '/ssl', '/etc/letsencrypt',
  ]);
  // Destinations nginx writes to — left to the image's own writable dirs.
  const writable = new Set(['/var/log/nginx', '/var/cache/nginx', '/run', '/tmp']);

  const binds = [
    `${hostTmpDir}/sites:/etc/nginx/sites:ro`,
    `${hostTmpDir}/conf:/etc/nginx/conf.d:ro`,
    `${hostTmpDir}/snippets:/etc/nginx/snippets:ro`,
    `${hostTmpDir}/streams:/etc/nginx/streams:ro`,
    `${hostTmpDir}/ssl:/ssl:ro`,
    `${hostTmpDir}/certs:/etc/letsencrypt:ro`,
  ];

  const inherited = [];
  try {
    const id = await getContainerId();
    const r  = await dockerCall('GET', `/containers/${encodeURIComponent(id)}/json`);
    for (const m of (r.body?.Mounts || [])) {
      if (!m.Source || !m.Destination) continue;
      if (overridden.has(m.Destination) || writable.has(m.Destination)) continue;
      binds.push(`${m.Source}:${m.Destination}:ro`);
      inherited.push(m.Destination);
    }
  } catch (e) {
    // Not fatal: the test still runs, but a config referencing an inherited
    // path (a GeoIP database, say) will fail in a way that looks like a config
    // error. Say so explicitly.
    console.warn('[test] Cannot inherit nginx mounts:', e.message);
  }
  return { binds, inherited };
}

async function testConfigEphemeral(srcDirs) {
  const sandboxRoot = path.join(DIR_GIT_WORK, '.sandbox');
  const tmpDir      = path.join(sandboxRoot, 'test_' + Date.now());
  const subDirs = ['sites', 'conf', 'snippets', 'streams', 'ssl', 'modules'];
  try {
    // Sweep sandboxes left behind by an interrupted run
    cleanStaleSandboxes(sandboxRoot);
    for (const d of subDirs) fs.mkdirSync(path.join(tmpDir, d), { recursive: true });

    // Copy nginx configs from Git work tree (or active dirs if no Git)
    const dirs = {
      sites:    srcDirs.sites    || DIR_SITES,
      conf:     srcDirs.conf     || DIR_CONF,
      snippets: srcDirs.snippets || DIR_SNIPPETS,
      streams:  srcDirs.streams  || DIR_STREAMS,
      ssl:      srcDirs.ssl      || DIR_SSL,
    };
    for (const [section, src] of Object.entries(dirs)) {
      if (!fs.existsSync(src)) continue;
      copyTree(src, path.join(tmpDir, section));   // recursive: ssl/cainternal/... etc.
    }

    // Copy Let's Encrypt certs (read-only, needed for ssl_certificate directives)
    // certs/ (Let's Encrypt) is never deployed, but the test container still needs
    // it: vhosts reference /etc/letsencrypt/live/... in ssl_certificate directives.
    // -L dereferences the symlinks LE keeps into archive/, so the real files land
    // in the sandbox.
    const certsLive = path.join(DIR_CERTS, 'live');
    if (fs.existsSync(certsLive)) {
      const certsTarget = path.join(tmpDir, 'certs');
      fs.mkdirSync(certsTarget, { recursive: true });
      try {
        // dereference: true == `cp -rL` (follow symlinks into real files) —
        // in-process, no shell involved (fix v12.21.1: this used to go
        // through lib/git.js#runCmd(), a template-string exec() call; moving
        // it off exec() entirely removes the temptation to ever interpolate
        // a path into a shell command again).
        fs.cpSync(certsLive, path.join(certsTarget, 'live'), { recursive: true, dereference: true });
      } catch {
        // Fallback for broken symlinks — `cp -r` copies a dangling symlink
        // itself rather than failing; dereference:false does the same here.
        try { fs.cpSync(certsLive, path.join(certsTarget, 'live'), { recursive: true, dereference: false }); }
        catch (e) { console.warn('[test] Could not copy Let\'s Encrypt certs:', e.message || e); }
      }
    }

    // Translate to a host path — Docker cannot bind-mount a path that only
    // exists inside this container.
    const hostTmpDir = await toHostPath(tmpDir);
    if (!hostTmpDir) {
      throw new Error(
        `Cannot map ${tmpDir} to a host path: no Docker mount covers ${DIR_GIT_WORK}. ` +
        `The deploy workspace must be a volume or bind mount (e.g. git-work:/git-work) ` +
        `so the ephemeral test container can actually read the configuration.`
      );
    }

    // Sanity check: refuse to report a green test on an empty config set.
    const copied = ['sites', 'conf', 'snippets', 'streams']
      .reduce((sum, d) => sum + listTreeFiles(path.join(tmpDir, d)).length, 0);
    if (copied === 0) {
      throw new Error('Refusing to test an empty configuration set (nothing was copied).');
    }

    const { binds: testBinds, inherited } = await buildTestBinds(hostTmpDir);

    // Get image
    const image = await getNginxImage();
    console.log(`[test] Ephemeral container: image=${image} host=${hostTmpDir} files=${copied}` +
                (inherited.length ? ` inherited=${inherited.join(',')}` : ''));

    // Create container
    const createBody = {
      Image: image,
      Cmd: ['nginx', '-t'],
      AttachStdout: true, AttachStderr: true,
      HostConfig: {
        AutoRemove: true,
        Binds: testBinds,
        // nginx resolves upstream hostnames while parsing the config, so an
        // isolated container fails on every `upstream` pointing at a real host.
        // Running on the production network gives the test the same DNS view as
        // the live server — otherwise the check cannot validate upstreams at all.
        NetworkMode: await getTestNetworkMode(),
      },
    };
    const created = await dockerCall('POST', '/containers/create', createBody);
    if (created.status !== 201) throw new Error(`Cannot create test container: ${JSON.stringify(created.body)}`);
    const cId = created.body.Id;

    // Start
    await dockerCall('POST', `/containers/${cId}/start`);

    // Wait for completion (max 30s)
    const waited = await dockerCall('POST', `/containers/${cId}/wait`);
    const exitCode = waited.body?.StatusCode ?? 1;

    // Get logs (multiplexed Docker stream)
    const logsRes = await dockerCall('GET', `/containers/${cId}/logs?stdout=1&stderr=1`);
    // Same fix as GoDNS and certbot: demux from the raw bytes via the shared,
    // TTY-aware helper, rather than re-encoding the already-decoded body back
    // into a buffer (lossy for non-ASCII output) and stripping frame headers
    // that a TTY-allocated container never sends in the first place.
    const logText = logsRes.rawBuffer ? docker.demuxToText(logsRes.rawBuffer) : '';

    // AutoRemove handles cleanup; also try explicit remove as fallback
    await dockerCall('DELETE', `/containers/${cId}?force=1`).catch(() => {});

    return { valid: exitCode === 0, exitCode, output: logText.trim(), image };
  } finally {
    // Clean up temp dir
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch {}
  }
}

async function deployFromGitWork(by) {
  const log  = [];
  const step = (msg, data) => { log.push({ msg, data, ts: new Date().toISOString() }); console.log('[deploy-local]', msg); };

  // Build merged test dirs: active dirs as base, git-work files override
  // This ensures the ephemeral test sees the full config (existing + new files)
  step('Building merged test dirs (active + git-work)');
  const MERGE_TMP = path.join(DIR_GIT_WORK, '.test-merge');
  const sectionMap = { sites: DIR_SITES, conf: DIR_CONF, snippets: DIR_SNIPPETS, streams: DIR_STREAMS, ssl: DIR_SSL };
  const srcDirs = {};

  for (const [section, activeDir] of Object.entries(sectionMap)) {
    // ssl/ is not deployed unless opted in — test against the live certs as-is,
    // otherwise nginx -t would validate files that never reach production.
    if (section === 'ssl' && !DEPLOY_SYNC_SSL) {
      srcDirs.ssl = DIR_SSL;
      continue;
    }
    const mergeDir  = path.join(MERGE_TMP, section);
    const gitWorkDir = path.join(DIR_GIT_WORK, section);
    fs.mkdirSync(mergeDir, { recursive: true });
    // Step 1: copy all active files as base
    copyTree(activeDir, mergeDir);
    // Step 2: overlay git-work files (new/updated files take priority)
    copyTree(gitWorkDir, mergeDir);
    srcDirs[section] = mergeDir;
  }

  step('Test config (ephemeral container — merged active + git-work)');
  const testResult = await testConfigEphemeral(srcDirs);
  step('Test result', testResult);

  // Cleanup merge tmp
  try { fs.rmSync(MERGE_TMP, { recursive: true, force: true }); } catch {}

  if (!testResult.valid) {
    logEvent('deploy.test.failed', { by, output: testResult.output }, 'deploy');
    throw { error: 'Config test failed', testResult, log };
  }

  step('Backup (ZIP)');
  const zipResult = await createBackupZip('pre-deploy').catch(e => ({ error: e.message }));
  step('Backup done', { zip: zipResult });

  // Copy ONLY from git-work (not from merge tmp which was already deleted)
  step('Copy configs to active dirs (additive — existing files preserved)');
  const dirs = { sites: DIR_SITES, conf: DIR_CONF, snippets: DIR_SNIPPETS, streams: DIR_STREAMS };
  if (DEPLOY_SYNC_SSL) dirs.ssl = DIR_SSL;
  let copiedCount = 0;
  const skipped = [];
  for (const [section, dst] of Object.entries(dirs)) {
    const src = path.join(DIR_GIT_WORK, section); // always git-work source
    if (!fs.existsSync(src)) continue;
    if (!isDirWritable(dst)) {
      skipped.push(section);
      step(`Skip ${section}: mounted read-only (${dst})`);
      continue;
    }
    fs.mkdirSync(dst, { recursive: true });
    for (const rel of listTreeFiles(src)) {
      if (rel.split(path.sep).some(isProtectedFile)) continue;
      const sp = path.join(src, rel), dp = path.join(dst, rel);
      try {
        fs.mkdirSync(path.dirname(dp), { recursive: true });
        fs.copyFileSync(sp, dp); copiedCount++;
      } catch (e) { step(`Copy failed ${section}/${rel}: ${e.code || e.message}`); }
    }
  }
  step(`Copied ${copiedCount} file(s) to active dirs${skipped.length ? ` (skipped read-only: ${skipped.join(', ')})` : ''}`);

  step('Reload nginx');
  const reloadResult = await execNginx('nginx -s reload');
  step('Reload done', reloadResult);

  logEvent('deploy.success', { by, zip: zipResult?.zipName, mode: 'local' }, 'deploy');
  return { ok: true, log, testResult, zipResult };
}

async function deployFromGit(by) {
  const log = [];
  const step = (msg, data) => { log.push({ msg, data, ts: new Date().toISOString() }); console.log('[deploy]', msg); };

  step('Pull Git');
  await gitPull();

  step('Test config (ephemeral container)');
  // Le test doit refleter l etat REEL apres deploiement, sur deux points :
  //  - ssl/ n est pas synchronise, ce sont les certificats vivants qui restent
  //    en place : les monter depuis git-work donnerait un /ssl vide et ferait
  //    echouer nginx -t sur chaque directive ssl_certificate.
  //  - les fichiers generes par une autre feature (blocklists.js) ne sont pas
  //    dans le depot Git non plus, mais eux SURVIVENT au deploiement (la
  //    boucle de suppression plus bas les ignore explicitement) — voir
  //    buildGitWorkTestSrcDirs() ci-dessus, qui les fusionne dans la vue de
  //    test pour que ce cas ne fasse pas echouer le test a tort.
  // dirs/srcDirs (git-work paths) restent la source de verite utilisee plus
  // bas par la copie/suppression — le test ephemere obtient sa PROPRE vue
  // via le helper partage, dont le dossier de fusion temporaire est detruit
  // juste apres le test.
  const dirs = { sites: DIR_SITES, conf: DIR_CONF, snippets: DIR_SNIPPETS, streams: DIR_STREAMS };
  if (DEPLOY_SYNC_SSL) dirs.ssl = DIR_SSL;
  const srcDirs = {
    sites:    path.join(DIR_GIT_WORK, 'sites'),
    conf:     path.join(DIR_GIT_WORK, 'conf'),
    snippets: path.join(DIR_GIT_WORK, 'snippets'),
    streams:  path.join(DIR_GIT_WORK, 'streams'),
  };

  const { testSrcDirs, cleanup } = buildGitWorkTestSrcDirs();
  testSrcDirs.ssl = DEPLOY_SYNC_SSL ? path.join(DIR_GIT_WORK, 'ssl') : DIR_SSL;

  const testResult = await testConfigEphemeral(testSrcDirs);
  cleanup();
  step('Test result', testResult);
  if (!testResult.valid) {
    logEvent('deploy.test.failed', { by, output: testResult.output }, 'deploy');
    throw { error: 'Config test failed', testResult, log };
  }

  step('Backup (ZIP + Git)');
  const zipResult = await createBackupZip('pre-deploy').catch(e => ({ error: e.message }));
  const gitResult = await gitBackupPush('pre-deploy').catch(e => ({ error: e.message }));
  step('Backup done', { zip: zipResult, git: gitResult });

  step('Copy configs to active dirs');
  const skipped = [];
  let removedCount = 0, copiedCount = 0;
  if (!DEPLOY_SYNC_SSL && fs.existsSync(path.join(DIR_GIT_WORK, 'ssl'))) {
    step('Skip ssl: disabled via DEPLOY_SYNC_SSL=false');
  }
  for (const [section, dst] of Object.entries(dirs)) {
    const src = srcDirs[section];
    if (!fs.existsSync(src)) continue;
    // Read-only mounts (typically ssl/ and certs/, managed by certbot) are skipped,
    // not fatal: the rest of the deploy must still go through.
    if (!isDirWritable(dst)) {
      skipped.push(section);
      step(`Skip ${section}: mounted read-only (${dst})`);
      continue;
    }
    fs.mkdirSync(dst, { recursive: true });
    const keep = rel => !rel.split(path.sep).some(isProtectedFile);
    const srcFiles = new Set(listTreeFiles(src).filter(keep));
    const dstFiles = listTreeFiles(dst).filter(keep);

    // Safety net: an empty source directory would wipe the destination. That is
    // almost always a mistake (repo folder holding only a .gitkeep) rather than
    // an intentional "delete everything", so deletions are skipped and reported.
    if (srcFiles.size === 0 && dstFiles.length > 0) {
      step(`Skip deletions in ${section}: source is empty, ${dstFiles.length} file(s) kept`);
    } else {
      // Remove files no longer in Git — never touch dotfiles (.gitkeep,
      // .gitignore) nor a file generated by another feature at runtime
      // (blocklist-ips.conf, blocklist-enforce.conf — see isGeneratedFile
      // above): those are intentionally absent from the repo and must
      // survive the mirror regardless.
      for (const rel of dstFiles) {
        if (srcFiles.has(rel)) continue;
        if (isGeneratedFile(path.join(dst, rel))) continue;
        try { fs.unlinkSync(path.join(dst, rel)); removedCount++; }
        catch (e) { step(`Remove failed ${section}/${rel}: ${e.code || e.message}`); }
      }
      pruneEmptyDirs(dst);
    }
    for (const rel of srcFiles) {
      const sp = path.join(src, rel), dp = path.join(dst, rel);
      // Fix v12.21.2 (audit finding DAC-10): the deletion loop above already
      // never REMOVES a generated file, but this copy loop used to overwrite
      // one unconditionally if the repo happened to contain a file at that
      // same path (a docker_*.conf/agent_*.conf accidentally committed, or
      // left over from an old backup restored into the repo). A Git deploy
      // must never clobber a live docker-autoconfig/agents-generated vhost —
      // the next detection cycle regenerates it from the current Docker
      // labels/agent manifest anyway, so the repo's stale copy would only
      // ever be wrong.
      if (isGeneratedFile(dp)) { step(`Skip copy ${section}/${rel}: fichier genere automatiquement (docker-autoconfig/agents)`); continue; }
      try {
        fs.mkdirSync(path.dirname(dp), { recursive: true });
        fs.copyFileSync(sp, dp); copiedCount++;
      } catch (e) { step(`Copy failed ${section}/${rel}: ${e.code || e.message}`); }
    }
  }
  step(`Copied ${copiedCount}, removed ${removedCount}${skipped.length ? `, skipped read-only: ${skipped.join(', ')}` : ''}`);

  step('Reload nginx');
  const reloadResult = await execNginx('nginx -s reload');
  step('Reload done', reloadResult);

  logEvent('deploy.success', { by, zip: zipResult?.zipName, gitTag: gitResult?.tag }, 'deploy');
  return { ok: true, log, testResult, zipResult, gitResult };
}
// ─── Routes ──────────────────────────────────────────────────────────────────
function register(router) {
  router.get('/api/git/test-connection', async ({ req, res, session, url, pathname }) => {
    if (!hasPerm(session, PERMS.DEPLOY)) return httpLib.forbidden(res);
    const g = getGitCfg();
    // Always return configured status with current env value for debugging
    if (!g.repoUrl) return send(res, 200, {
      configured: false,
      error: 'GIT_REPO_URL not set (env or git.yml)',
      // SEC-07 fix (v12.21.1): used to echo the raw env value back to any
      // DEPLOY-permission caller (an operator, or a deploy_ci token). Never a
      // credential by itself, but redacted the same way for consistency and
      // because an https://TOKEN@host URL could end up in GIT_REPO_URL too.
      envValue: redactUrl(process.env.GIT_REPO_URL) || '(empty)',
    });
    try {
      const result = await gitTestConnection();
      return send(res, 200, { configured: true, ...result });
    } catch(e) {
      return send(res, 200, {
        configured: true, ok: false,
        url: redactUrl(g.repoUrl),
        authMethod: g.token ? 'https-token' : g.sshKey ? 'ssh-key' : 'none',
        // e.error/e.stderr already redacted by lib/git.js#runCmd() (SEC-07)
        error: e.error || e.message,
        stderr: e.stderr || '',
        hint: e.stderr?.includes('403') || e.stderr?.includes('Forbidden')
          ? 'HTTP 403: token sans droits write:repository (Forgejo: Settings > Applications > Token)'
          : e.stderr?.includes('not found') || e.stderr?.includes('404')
          ? 'HTTP 404: depot introuvable ou token invalide'
          : e.stderr?.includes('authentication')
          ? 'Erreur authentification: verifier GIT_TOKEN'
          : null,
      });
    }
  });

  router.get('/api/backups/download', async ({ req, res, session, url, pathname }) => {
    if (!hasPerm(session, PERMS.DEPLOY)) return httpLib.forbidden(res);
    const name = (url.searchParams.get('name') || '').replace(/[/\\]/g, '');
    if (!name || !name.endsWith('.zip')) return httpLib.badRequest(res, 'Invalid name');
    const fp = path.join(DIR_BACKUPS, name);
    if (!fp.startsWith(DIR_BACKUPS)) return httpLib.forbidden(res, 'Access denied');
    if (!fs.existsSync(fp)) return httpLib.notFound(res, 'Not found');
    const stat = safeStat(fp);
    res.writeHead(200, {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${name}"`,
      'Content-Length': stat.size,
      'Cache-Control': 'no-cache',
    });
    fs.createReadStream(fp).pipe(res);
    return;
  });

  router.post('/api/git/init-backup-branch', async ({ req, res, session, url, pathname }) => {
    if (!hasPerm(session, PERMS.DEPLOY)) return httpLib.forbidden(res);
    try {
      const result = await gitCreateBackupBranch();
      logEvent('git.backup-branch.init', { by: session.username, ...result }, 'deploy');
      return send(res, 200, result);
    } catch(e) { return send(res, 500, { error: e.error || e.message }); }
  });

  router.get('/api/git/status', async ({ req, res, session, url, pathname }) => {
    // Read-only, no per-action gating: any deploy token (whatever its own
    // `actions` allowlist) may check status before deciding what to trigger.
    if (!hasPerm(session, PERMS.DEPLOY)) return httpLib.forbidden(res);
    const g = getGitCfg();
    if (!g.repoUrl) return send(res, 200, { configured: false });
    try {
      validateBranch(g.branch, 'branch');
      if (g.backupBranch) validateBranch(g.backupBranch, 'backup_branch');
      await ensureGitRepo();
      const log         = await runCmd(['-C', DIR_GIT_WORK, 'log', '-10', '--oneline']).catch(() => ({ stdout: '' }));
      const currentHash = await runCmd(['-C', DIR_GIT_WORK, 'rev-parse', 'HEAD']).catch(() => ({ stdout: '' }));
      const remoteHash  = await runCmd(['-C', DIR_GIT_WORK, 'rev-parse', `origin/${g.branch}`]).catch(() => ({ stdout: '' }));
      const diff        = await gitDiff().catch(() => []);
      const backupCheck = await runCmd(['-C', DIR_GIT_WORK, 'ls-remote', '--heads', effectiveRepoUrl(g), g.backupBranch]).catch(() => ({ stdout: '' }));
      return send(res, 200, {
        configured: true, repo: redactUrl(g.repoUrl), branch: g.branch,
        backupBranch: g.backupBranch,
        backupBranchExists: backupCheck.stdout.trim().length > 0,
        currentHash: currentHash.stdout.slice(0, 12),
        remoteHash:  remoteHash.stdout.slice(0, 12),
        upToDate: currentHash.stdout.trim() === remoteHash.stdout.trim(),
        recentCommits: log.stdout.split('\n').filter(Boolean),
        diff,
      });
    } catch(e) { return send(res, 200, { configured: true, error: e.message || e.error }); }
  });

  router.post('/api/git/pull', async ({ req, res, session, url, pathname }) => {
    if (!hasPerm(session, PERMS.DEPLOY) || !deployTokenAllows(session, 'pull')) return httpLib.forbidden(res);
    if (!getGitCfg().repoUrl) return httpLib.badRequest(res, 'GIT_REPO_URL not configured');
    try {
      const r    = await gitPull();
      const diff = await gitDiff();
      logEvent('git.pull', { by: session.username, ...r }, 'deploy');
      return send(res, 200, { ok: true, ...r, diff });
    } catch(e) { return send(res, 500, { error: e.error || e.message, ...e }); }
  });

  router.post('/api/git/test', async ({ req, res, session, url, pathname }) => {
    if (!hasPerm(session, PERMS.DEPLOY) || !deployTokenAllows(session, 'test')) return httpLib.forbidden(res);
    // Meme helper que deployFromGit() : sans lui, un vhost qui inclut deja
    // un fichier genere par une autre feature (blocklist-enforce.conf,
    // jamais versionne dans le depot Git par construction) fait echouer ce
    // test standalone a tort, puisque git-work seul ne l a jamais.
    const { testSrcDirs, cleanup } = buildGitWorkTestSrcDirs();
    testSrcDirs.ssl = path.join(DIR_GIT_WORK, 'ssl');
    try {
      const result = await testConfigEphemeral(testSrcDirs);
      logEvent('git.test', { by: session.username, valid: result.valid }, 'deploy');
      // A CI caller needs the HTTP status itself to reflect pass/fail (a
      // `curl --fail` step, a GitHub/GitLab/Forgejo job) — 200 regardless of
      // `valid` would make every invalid config look like a green build.
      // 422 mirrors what /api/git/deploy already returns when ITS own
      // pre-reload test fails, for the same reason.
      return send(res, result.valid ? 200 : 422, result);
    } catch(e) { return send(res, 500, { error: e.error || e.message, ...e }); }
    finally { cleanup(); }
  });

  router.post('/api/git/deploy', async ({ req, res, session, url, pathname }) => {
    if (!hasPerm(session, PERMS.DEPLOY) || !deployTokenAllows(session, 'deploy')) return httpLib.forbidden(res);
    if (!getGitCfg().repoUrl) return httpLib.badRequest(res, 'GIT_REPO_URL not configured');
    try {
      const result = await deployFromGit(session.username);
      return send(res, 200, result);
    } catch(e) { return send(res, e.testResult ? 422 : 500, { error: e.error || e.message, ...e }); }
  });

  router.get('/api/backups', async ({ req, res, session, url, pathname }) => {
    if (!hasPerm(session, PERMS.DEPLOY)) return httpLib.forbidden(res);
    // gitConfigured lets the frontend hide/explain the "Restaurer" button
    // without a round trip of its own — see POST /api/backups/restore below
    // for why restoring a local ZIP is disabled once Git is configured.
    return send(res, 200, { backups: listBackups(), dir: DIR_BACKUPS, keep: BACKUP_KEEP, gitConfigured: !!getGitCfg().repoUrl });
  });

  router.post('/api/backups', async ({ req, res, session, url, pathname }) => {
    if (!hasPerm(session, PERMS.DEPLOY) || !deployTokenAllows(session, 'backup')) return httpLib.forbidden(res);
    const body      = await parseBody(req);
    const label     = (body.label || 'manual').replace(/[^a-zA-Z0-9_-]/g, '-').slice(0, 40);
    const mode      = body.mode || 'local'; // 'local' | 'git' | 'both'
    const doLocal   = mode === 'local' || mode === 'both';
    const hasGitRepo = !!getGitCfg().repoUrl;
    const doGit     = (mode === 'git'  || mode === 'both') && hasGitRepo;
    try {
      const zipResult = doLocal
        ? await createBackupZip(label)
        : { skipped: true, reason: 'git-only mode' };

      const gitResult = doGit
        ? await gitBackupPush(label).catch(e => ({ ok: false, error: e.message || e.error || e.stderr }))
        : { skipped: true, reason: !hasGitRepo ? 'GIT_REPO_URL not configured' : 'local-only mode' };

      logEvent('backup.manual', { by: session.username, mode, zip: zipResult.zipName, git: gitResult }, 'backup');
      return send(res, 201, { ok: true, mode, zip: zipResult, git: gitResult });
    } catch(e) { return send(res, 500, { error: e.message || e.error }); }
  });

  // POST /api/backups/restore — bug fixed in v12.46.0 (retour utilisateur):
  // this used to work regardless of Git, so restoring a local ZIP over live
  // configuration while Git is configured silently put the two out of sync
  // — the dashboard's files would stop matching what the repository (the
  // actual source of truth once Git is set up) thinks is deployed, with
  // nothing surfacing the drift until the next diff/deploy. Same rule as
  // ALLOW_CREATE/ALLOW_EDIT just above in features/configs.js: once Git is
  // configured, changes are expected to flow through the repository —
  // reverting the unwanted commit and redeploying is the equivalent of a
  // "restore" that Git already knows about.
  router.post('/api/backups/restore', async ({ req, res, session, url, pathname }) => {
    if (!hasPerm(session, PERMS.DEPLOY)) return httpLib.forbidden(res);
    if (getGitCfg().repoUrl) {
      return send(res, 403, {
        error: 'Restoring a local backup is disabled while Git is configured — '
             + 'revert the unwanted commit in your repository and redeploy via Git instead',
      });
    }
    const body = await parseBody(req);
    if (!body.name) return httpLib.badRequest(res, 'name required');
    const zipPath = path.join(DIR_BACKUPS, body.name);
    if (!fs.existsSync(zipPath)) return httpLib.notFound(res, 'Backup not found');
    if (!zipPath.startsWith(DIR_BACKUPS)) return httpLib.forbidden(res, 'Access denied');
    try {
      const preBkp = await createBackupZip('pre-restore');
      const restored = await restoreBackupZip(zipPath);
      await execNginx('nginx -s reload');
      logEvent('backup.restore', { by: session.username, from: body.name, preBkp: preBkp.zipName }, 'backup');
      return send(res, 200, { ok: true, restored, preBkp });
    } catch(e) { return send(res, 500, { error: e.message || e.error }); }
  });

  router.addPrefix('DELETE', '/api/backups/', async ({ req, res, session, url, pathname }) => {
    if (!hasPerm(session, PERMS.DEPLOY)) return httpLib.forbidden(res);
    const name = decodeURIComponent(pathname.split('/')[3] || '');
    const fp = path.join(DIR_BACKUPS, name);
    if (!fp.startsWith(DIR_BACKUPS) || !name.endsWith('.zip')) return httpLib.forbidden(res, 'Access denied');
    if (!fs.existsSync(fp)) return httpLib.notFound(res, 'Not found');
    fs.unlinkSync(fp);
    logEvent('backup.deleted', { by: session.username, name }, 'backup');
    return send(res, 200, { ok: true });
  });
}

module.exports = {
  register, setDeps, isGeneratedFile, getGeneratedFilesList, GENERATED_FILE_PREFIXES,
  getNginxImage, buildTestBinds, testConfigEphemeral,
  deployFromGit, deployFromGitWork,
  cleanStaleSandboxes, cleanLegacyTestDirs,
};
